### ISSUE TITLE
registerFont

### ISSUE THREAD

**Issue by AceAsin** [kyranet/canvas-constructor#352]
Registering a font works fine, as intended on local machine, but not when it gets deployed. The fonts don't register.

**Comment by kyranet** [comment]
I can reproduce, the fonts registered on Windows and on Debian 10 differ.

I guess you can try looking at https://github.com/Automattic/node-canvas/issues and see if there's a fix for it, `canvas-constructor` simply re-exports the `registerFont` function.

**Comment by AceAsin** [comment]
Now that I see. The fonts have indeed been working all along. 

The problem is that I'm using fonts that support some special unicode characters and emojis, so that they don't display as tofu. 

It works fine locally, the fonts are able to change original text and tofu into what they're supposed to look like. But when I host and deploy my application, it converts original text fine, using the fonts intended, but not the special characters, they end up displaying as tofu.

I probably need to do something else that supports tofu, so I don't have to use the rest of the fonts.

**Comment by kyranet** [comment]
Closing as 4.0.0 does not longer expose `registerFont`. Please reach out the aforementioned link for support from `canvas`'s maintainers.

Alternatively, you can try installing the fonts into your OS, as per the docs here: https://github.com/Automattic/node-canvas#registerfont

**Comment by AceAsin** [comment]
I ended up adding more fonts on my assets folder to register, that supported the missing mathematical symbol unicode text, also installing the fonts on the OS itself, with emoji support, when deploying and everything is showing up now. 

If I come across some unicode text not showing up again, then the best bet is to do the same, look for a font that supports it, add it to my asset folder and installing it on the OS when deploying.
