### ISSUE TITLE
TypeError: Canvas.resolveImage is not a function

### ISSUE THREAD

**Issue by zyiang1928** [kyranet/canvas-constructor#356]
Anyone can help me? This is the code that I made
```
async function createCanvas() {
        const avatar = await Canvas.resolveImage(message.author.displayAvatarURL({ format: 'png', dynamic: true, size: 1024 }));
    
        return new Canvas(1400, 1400)
            .setShadowColor("rgba(22, 22, 22, 0.3)")
            .setShadowOffsetY(5)
            .setShadowBlur(10)
            .printImage(avatar, 0, 0, 1400, 1400)
            .toBufferAsync()
     }
     
     message.channel.send(`**Avatar's for ${message.author.tag}**`, {
       files: [{
          attachment: await createCanvas(),
          name: "avatar.png"
       }]
     });
```

**Comment by kyranet** [comment]
What is the environment (browser, node.js) and which module definition are you using (UMD, AMD, requirejs, CommonJS, or ESM)?

And not less importantly, what's `Canvas` defined as, and what is your canvas-constructor version?

**Comment by kyranet** [comment]
Actually, reading your code, you're using discord.js, so you're 99.99% likely to be using Node.js with CJS.

I also see that `Canvas` is defined as the library's class, not the library's exports.

`resolveImage` is not a static method on `Canvas`, it's a separate export. To fix this, you need to do this:

```javascript
const { Canvas, resolveImage } = require('canvas-constructor');
```

**Comment by zyiang1928** [comment]
Oh okay thanks
