### ISSUE TITLE
How to add a background image?

### ISSUE THREAD

**Issue by Cyanic76** [kyranet/canvas-constructor#363]
Hello, I got a quick question:

I'm getting `TypeError: Image or Canvas expected` when using the following code.

```js
const resultbg = await fetch("https://cdn.discordapp.com/attachments/725418862346240070/747769058283225158/Capture.PNG ");
    const bg = await resultbg.buffer();
    let img = new Canvas(400,180)
    .printImage(bg, 0, 0, 400, 180)
    .setColor("#ffffff")
    .setTextSize(27)
    .addText(name, 10, 10) // name = mentioned user or author's username
    .setTextSize(18) // rest of profile...
```
I've also tried using `Canvas.resolveImage(image)` but `TypeError: Canvas.resolveImage is not a function` shows up.

Is the picture not in an acceptable format? What did I forgot to do? How do I fix this?

**Comment by kyranet** [comment]
You import `resolveImage` from the module, not from the class.

```javascript
const { Canvas, resolveImage } = require('canvas-constructor');
```

---

Just curious, what led you to the assumption that `resolveImage` is a static property of `Canvas`?

**Comment by Cyanic76** [comment]
Well, I thought I had to import `resolveImage` from the class but thanks for telling me that.

But, another question/bug : the error `TypeError: Image or Canvas expected` show up when using an image URL like the link to the image i provided above. How do I fix this?

**Comment by kyranet** [comment]
By using `resolveImage` instead of `await (await fetch(...)).buffer()`.
