### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by ChanceTheDev-1** [kyranet/canvas-constructor#365]
Hi so I am trying to do a background image but it isnt working.. I am trying to do the image with a api..

![image](https://user-images.githubusercontent.com/69983078/93942370-2933c800-fd28-11ea-8006-55066f14d545.png)
![image](https://user-images.githubusercontent.com/69983078/93942384-305ad600-fd28-11ea-9cb9-e54cd1818de4.png)

**Comment by kyranet** [comment]
`nowplaying` is a `Promise<Buffer>`, you forgot to `await`.

**Comment by ChanceTheDev-1** [comment]
So where do I post the await?

**Comment by kyranet** [comment]
`await new`
