### ISSUE TITLE
bug: Fuction not available 

### ISSUE THREAD

**Issue by AriaFantom** [kyranet/canvas-constructor#371]
**I want to draw a image normally and just encountered this error**

The code is here - https://pastebin.com/51Rci7TL

And error is 
```
node:83980) UnhandledPromiseRejectionWarning: TypeError: (intermediate value).printImage(...).setColor(...).addCircle is not a function
    at module.exports.run (/home/ubuntu/Youva-Bot/src/Commands/Owner/test.js:23:10)```

**Comment by kyranet** [comment]
It's printCircle, please read the [documentation](https://canvasconstructor.js.org).
