### ISSUE TITLE
bug: imports don't work

### ISSUE THREAD

**Issue by ChikoShidori** [kyranet/canvas-constructor#485]
**Describe the bug**

It just won't let me work when importing the file the right way and without data types

**To Reproduce**

1. Try to import skia file or anything else

**Expected behavior**

0 errors importing the file

**Screenshots**

https://user-images.githubusercontent.com/53100578/172073797-0f9c2ef1-4973-48ec-a592-e542498bdd5f.mp4

**Additional context**

**Comment by kyranet** [comment]
I thought this was supported in TS 4.7, but apparently not? https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing

I suppose I'll revert the removal of the top-level files.
